### ISSUE TITLE
No border around legend symbols

### ISSUE THREAD

**Issue by michmuel** [openoereb/pyramid_oereb_mfp#112]
There should be no black border around the legend symbols.

Current version:
![Screenshot from 2022-05-16 16-26-31](https://user-images.githubusercontent.com/77100084/168616195-1e657756-fe9d-45bd-94d9-a12f3e9728f1.png)

Specifications:
![Screenshot from 2022-05-16 16-27-13](https://user-images.githubusercontent.com/77100084/168616297-397c10b6-dc93-4308-9a82-b4afc5ba7b9b.png)

**Comment by voisardf** [comment]
yes, it's an easy fix in the templates. For the legend I think it's just about removing those lines:
https://github.com/openoereb/pyramid_oereb_mfp/blob/master/print-apps/oereb/topiclegend.jrxml#L41-L43
and the same in the topiclegend.
Personally, I'd removed the box by opening the template in the GUI of Jasper Reports to be sure not to miss anything.
If I have a few spare minutes tomorrow, I'll fix it and create a PR

**Comment by michmuel** [comment]
Thanks!

**Comment by voisardf** [comment]
Solved by PR https://github.com/openoereb/pyramid_oereb_mfp/pull/113
