### ISSUE TITLE
"öffentlich-rechtliche" Eigentumsbeschränkungen in page overview - naming convention

### ISSUE THREAD

**Issue by MaxHoeferGEOINFO** [openoereb/pyramid_oereb_mfp#115]
Hi all

should the "Übersicht ÖREB-Themen" page not have the following naming convention? 

![image](https://user-images.githubusercontent.com/54711581/177267734-8e194d4f-1081-4a66-a428-b8aeb7169724.png)

Sorry for all the german, I don't know how those explicit points are named in english.
Cheers
Max

**Comment by voisardf** [comment]
@MaxHoeferGEOINFO Hi Max, looks like we missed this, sorry.
I'll adapt the property files. It seems to have changend in the german version only

**Comment by voisardf** [comment]
Will be fixed by PR https://github.com/openoereb/pyramid_oereb_mfp/pull/116

**Comment by peterschaer** [comment]
The V+D has published an xml file containing all the text of the pdf extract:

* direct link: https://www.cadastre.ch/content/cadastre-internet/de/manual-oereb/modell/frame/_jcr_content/contentPar/tabs_copy_copy_copy_/items/dokumente/tabPar/downloadlist_269503579/downloadItems/90_1646229667044.download/OeREBKRM_Vx_x_AuszugTexte_20220301.zip
* the link is included here: https://www.cadastre.ch/de/manual-oereb/modell/frame.html

If you look at this xml file you can see, that it contains e.g. "Eigentumsbeschränkungen, welche das Grundstück %s in %s%s betreffen." The texts in the property files probably come from this xml file. There is a difference between the xml and the Weisung. I don't know which one is correct, but the V+D probably doesn't know that itself. We in Berne stick to the xml file and we will see what V+D says when they verify our extract.

**Comment by voisardf** [comment]
@peterschaer thanks for linking the file - I was looking for it, but in the wrong place (models.geo.admin.ch). I'll check with V+D

**Comment by voisardf** [comment]
@MaxHoeferGEOINFO @peterschaer : V+D will publish the new xml on the Öreb-Blog if it's not done already
