### ISSUE TITLE
"Allgemeine Informationen" split up over two pages

### ISSUE THREAD

**Issue by MaxHoeferGEOINFO** [openoereb/pyramid_oereb_mfp#117]
Hi all

The Swisstopo complained, that the "allgemeine Informationen" can be split up over two pages, depending on the "Übersicht ÖREB Themen" size. 
![image](https://user-images.githubusercontent.com/54711581/189671085-143bd745-0800-4434-a678-d72dc13f27b4.png)
This is not according to their standards Kapitel 3.3.2 der Weisung "ÖREB-Kataster: Inhalt und Darstellung des statischen Auszugs".

I assume this is something everyone has now? 
Cheers
Max

**Comment by peterschaer** [comment]
We also have a lot of those cases:

![allg](https://user-images.githubusercontent.com/3659322/191177691-1893ece2-9f1d-49d8-9ea2-a154d781c9cc.PNG)

but swisstopo has not yet given us feedback on their acceptance tests. So I expect them to report this as an issue...

**Comment by voisardf** [comment]
@MaxHoeferGEOINFO @peterschaer should be fixed with latest PR
