### ISSUE TITLE
adjust term "ÖREBKataster" to "ÖREB-Kataster" in information text for QR code

### ISSUE THREAD

**Issue by PeterMayrhoferGEOINFO** [openoereb/pyramid_oereb_mfp#134]
Hi all,

We got the remark from a customer that the term "ÖREBKataster" is written different in the information text for the QR code than in the other text passages ("ÖREB**-**Kataster"). 
Could the text please be changed from "ÖREBKataster" to "ÖREB-Kataster"?
![2023-05-05_11h01_42](https://user-images.githubusercontent.com/132656610/236418070-a33ad259-7a13-405d-bbd3-da4964e5c998.png)

Thank you very much.

Best
Peter

**Comment by jwkaltz** [comment]
Hi Peter
You can change this text in your project file print-apps/oereb/Report_de.properties

To make sure you do not lose this change in future updates, I will change it in the standard templates as well.

Wolfgang

**Comment by PeterMayrhoferGEOINFO** [comment]
Hi Wolfgang,

great, thanks a lot  for the quick fix :)

Best regards,
Peter
