### ISSUE TITLE
Remove term "(Rechtskräftig)" for valid topics in overview of topics

### ISSUE THREAD

**Issue by PeterMayrhoferGEOINFO** [openoereb/pyramid_oereb_mfp#136]
Hi everyone, 

we got the remark from a client concerning the PDF-report that the overview of topics includes the term "(Rechtskräftig)" for topics that are valid: 
![image](https://github.com/openoereb/pyramid_oereb_mfp/assets/132656610/cec9f01e-20eb-41a9-9f58-8becc42771ac)

According to the directive of swisstopo the legal status should only be added when a topic is affected by a change (see page 14 and page 35 in
https://www.cadastre.ch/de/services/publication.detail.document.html/cadastre-internet/de/documents/oereb-weisungen/Weisung-OEREB-statischer-Auszug-de.pdf.html)

We therefore think that the legal status should be left out for valid topics.
Could the print template please be adjusted so that the legal status for valid topics is not printed anymore?
Our developer thinks that this is caused by the following code line: 
https://github.com/openoereb/pyramid_oereb_mfp/blob/756c76280965e1b868d49b89fb62087c72ee4c4f/print-apps/oereb/topicTitle.jrxml#L34

Thank you very much. 

Best,
Peter

**Comment by peterschaer** [comment]
Hi Peter

You're right. Fortunately, this has already been addressed (#128 ). Pyramid_oereb_mfp should actually already behave correctly.

Best regards
Peter

**Comment by PeterMayrhoferGEOINFO** [comment]
Hi Peter

Thanks a lot for your quick reply. Great that this topic has already been covered. 
Therefore, this issue can be closed. 

Best regards
Peter

**Comment by sitj-marc** [comment]
Hello,
Thank you for this information.

We are using the latest version of pyramid_oereb_mfp 2.4.2 but still we have the term "En Vigueur" appearing in the table of contents.

![image](https://github.com/openoereb/pyramid_oereb_mfp/assets/3088758/82c3eace-67e5-4629-9ab3-2297f30833ef)

Best Regards
Marc
