### ISSUE TITLE
The scale in the map section must always be rounded to values of 5 or 10

### ISSUE THREAD

**Issue by ruben-grossmann** [openoereb/pyramid_oereb_mfp#146]
Hi

When the federal government accepted our ÖREB portal for AI/AR/SG, there was still one less urgent point of criticism. The point was that the scale in the map section must always be rounded to values of 5 or 10.

On small real estates there are steps of 2. One example of AI:
https://oereb.ai.ch/ktai/wsgi/oereb/extract/pdf?EGRID=CH487459417776

It's written in this document: https://backend.cadastre-manual.admin.ch/fileservice/sdweb-docs-prod-cadastremanch-files/files/2024/03/07/4e7edcc6-897d-40b4-ae1b-db6c76669d56.pdf

On Page 13 there's this text:

> Das angezeigte Massstabsymbol ist zu verwenden mit auf 5er- resp. 10er-Werte gerundeten Einheiten. Das Symbol ist mit einem weissen Halo zu umgeben.

> The displayed scale symbol is to be used with units rounded to 5 or 10 values. The symbol is to be surrounded by a white halo.

I checked other cantons who use pyramid_oereb and they have the same problem:
https://api.oereb.bs.ch/extract/pdf?EGRID=CH482589677979
https://sitn.ne.ch/crdppf/extract/pdf?EGRID=CH318783497885
https://oereb.geo.bl.ch/extract/pdf?EGRID=CH327008073942

Are there any plans to fix this?

Thanks,
Ruben from GEOINFO.

**Comment by svamaa** [comment]
Hi Ruben
thanks for reporting this. Currently, there are no plans to fix this, yet.
As far as I understand this, the default behaviour of the scalebar is to find its own width for a given scale. I don't know of any configuration to define the behaviour. And it only occurs for large scales.
However, for large scales (eg. 1:250) the scalebar might be a bit different, when only two subunits were to be displayed. (0-5m & 5-10m).
@jwkaltz , is this behaviour known to you?

**Comment by jwkaltz** [comment]
> Hi Ruben thanks for reporting this. Currently, there are no plans to fix this, yet. As far as I understand this, the default behaviour of the scalebar is to find its own width for a given scale. I don't know of any configuration to define the behaviour. And it only occurs for large scales. However, for large scales (eg. 1:250) the scalebar might be a bit different, when only two subunits were to be displayed. (0-5m & 5-10m). @jwkaltz , is this behaviour known to you?

Hi Anne, Hi Ruben
No, I was not aware of this behavior. I can investigate further if you wish.

**Comment by ruben-grossmann** [comment]
Hey Anne and Wolfgang
Thanks for your answers. We are currently in discussions with swisstopo about this. I don't know yet if we want this to be investigated further. I will let you know if I have new informations.

**Comment by Marco-Scheuble** [comment]
Hi all
I talked to swisstopo about this issue and they will remove the respective requirement from the directive ( [Weisung] https://backend.cadastre-manual.admin.ch/fileservice/sdweb-docs-prod-cadastremanch-files/files/2024/03/07/4e7edcc6-897d-40b4-ae1b-db6c76669d56.pdf) .

Answer of Swisstopo:
" ... wir haben entschieden, dass wir auf die Korrektur dieses Mangels verzichten.
Entsprechend diesem Entscheid, haben wir einen RfC bezüglich der Weisung zum statischen Auszug zu diesem Punkt erfasst, welcher bei der nächsten Gelegenheit in der Weisung durchschlagen wird."

**Comment by ruben-grossmann** [comment]
Well then nothing needs to be done. I will close the issue.
