### ISSUE TITLE
small vertical spacing when line breaks in toc titles

### ISSUE THREAD

**Issue by peterschaer** [openoereb/pyramid_oereb_mfp#18]
If a heading in the toc is very long and is wrapped on two lines the vertical spacing to the following horizontal line is too small. it is visibly smaller than in the case of no line break.

sample extract:
[20191009111931_extract.pdf](https://github.com/openoereb/pyramid_oereb_mfp/files/3706571/20191009111931_extract.pdf)

vertical spacing too small:
![vertical_spacing1](https://user-images.githubusercontent.com/3659322/66469313-e8479280-ea87-11e9-9fac-ccc8b44c237f.PNG)

vertical spacing ok:
![vertical_spacing2](https://user-images.githubusercontent.com/3659322/66469312-e8479280-ea87-11e9-9a96-ba7082584764.PNG)

**Comment by voisardf** [comment]
fixed by PR: https://github.com/openoereb/pyramid_oereb_mfp/pull/31

**Comment by voisardf** [comment]
fixed by PR https://github.com/openoereb/pyramid_oereb_mfp/pull/31
