### ISSUE TITLE
horizontal line missing in case of page break

### ISSUE THREAD

**Issue by peterschaer** [openoereb/pyramid_oereb_mfp#19]
We have a special situation in one of our pdf extracts:

![port](https://user-images.githubusercontent.com/3659322/66473122-f0ef9700-ea8e-11e9-886b-127b389688fe.PNG)

the page break happens inside the "Zuständige Stelle" section. In this case the horizontal line between the "Weitere Informationen und Hinweise"-section and the "Zuständige Stelle"-section is not displayed. If you look closely you will notice that the horizontal line is displayed on the top of the next page. We see two lines very close together:

![port2](https://user-images.githubusercontent.com/3659322/66473404-783d0a80-ea8f-11e9-910c-95a89f9f2968.PNG)

the complete example extract:

[20191009121543_extract.pdf](https://github.com/openoereb/pyramid_oereb_mfp/files/3706784/20191009121543_extract.pdf)

**Comment by voisardf** [comment]
fixed by PR https://github.com/openoereb/pyramid_oereb_mfp/pull/33
