### ISSUE TITLE
small vertical spacing when line breaks in section label

### ISSUE THREAD

**Issue by peterschaer** [openoereb/pyramid_oereb_mfp#21]
if a label on the plr pages is too long and is wrapped on two lines the vertical space below is too small:

![label1](https://user-images.githubusercontent.com/3659322/66474940-948e7680-ea92-11e9-8437-292bf6e19065.PNG)

if the label is only on one page the vertical space is ok:

![label2](https://user-images.githubusercontent.com/3659322/66474961-9fe1a200-ea92-11e9-9b49-943558ccdadc.PNG)

**Comment by voisardf** [comment]
fixed by PR https://github.com/openoereb/pyramid_oereb_mfp/pull/33
