### ISSUE TITLE
no line break when Zuständige Stelle is too long

### ISSUE THREAD

**Issue by peterschaer** [openoereb/pyramid_oereb_mfp#22]
If the name of Zuständige Stelle is very long it should be wrapped on two lines. But that is not happening:

![zust2](https://user-images.githubusercontent.com/3659322/66475252-37df8b80-ea93-11e9-8e07-d91477ea9a01.PNG)

In this example the complete name of Zuständige Stelle is:
Stadt Bern (für Auskünfte zu Bauvorhaben: Bauinspektorat der Stadt Bern).
Right now the text is cut off. no line break is happening.

**Comment by voisardf** [comment]
fixed by PR https://github.com/openoereb/pyramid_oereb_mfp/pull/33
