### ISSUE TITLE
link to complete legend is indented

### ISSUE THREAD

**Issue by peterschaer** [openoereb/pyramid_oereb_mfp#23]
The link to the complete legend is indented. But according to the Weisung that should not be the case:

![legende](https://user-images.githubusercontent.com/3659322/66475538-ce13b180-ea93-11e9-96a4-e1f514d981a2.PNG)

![weisung](https://user-images.githubusercontent.com/3659322/66475711-28147700-ea94-11e9-8754-06d3080bed8b.PNG)

**Comment by voisardf** [comment]
fixed by PR https://github.com/openoereb/pyramid_oereb_mfp/pull/33
