### ISSUE TITLE
Vertical space on toc page too big

### ISSUE THREAD

**Issue by peterschaer** [openoereb/pyramid_oereb_mfp#24]
The vertical space between the plr heading and the "page" label in the toc is too big:

![toc1](https://user-images.githubusercontent.com/3659322/66475865-7fb2e280-ea94-11e9-9d49-b613d156b152.PNG)

**Comment by voisardf** [comment]
fixxed by PR: https://github.com/openoereb/pyramid_oereb_mfp/pull/31

**Comment by voisardf** [comment]
fixed by PR https://github.com/openoereb/pyramid_oereb_mfp/pull/31
