### ISSUE TITLE
Vertical space above "Zuständige Stelle" is too small

### ISSUE THREAD

**Issue by peterschaer** [openoereb/pyramid_oereb_mfp#25]
The vertical space above the "Zuständige Stelle" label is smaller than on the other labels:

![zust1](https://user-images.githubusercontent.com/3659322/66476327-9148ba00-ea95-11e9-833c-247a6aa00103.PNG)

**Comment by voisardf** [comment]
fixed by PR https://github.com/openoereb/pyramid_oereb_mfp/pull/33
