### ISSUE TITLE
subunit_of_land_register not printed on TOC-page in PDF extract

### ISSUE THREAD

**Issue by peterschaer** [openoereb/pyramid_oereb_mfp#27]
subunit_of_land_register is not printed on the TOC-page in PDF extract. Right now it looks like this:

![gbkreis2_neu](https://user-images.githubusercontent.com/3659322/48472915-95257b00-e7f7-11e8-95a6-baf075f3a42c.PNG)

but it should look like this - according to the _weisung_:

![gbkreis2_alt](https://user-images.githubusercontent.com/3659322/48472948-a40c2d80-e7f7-11e8-8fb2-7ff3804c3e32.PNG)

**Comment by voisardf** [comment]
Fixed by PR https://github.com/openoereb/pyramid_oereb_mfp/pull/32
