### ISSUE TITLE
CertificationAtWeb not printed in PDF extract

### ISSUE THREAD

**Issue by peterschaer** [openoereb/pyramid_oereb_mfp#29]
While Extract.CertificationAtWeb is present in JSON/XML it is not printed in PDF extract.

![begl_neu](https://user-images.githubusercontent.com/3659322/48472530-d1a4a700-e7f6-11e8-92be-aa53d7210779.PNG)

**Comment by voisardf** [comment]
If I call a pdf with getspec; I get  _Certification_ as text (from multilingual) but _CertificationAtWeb_ which contains the URL as multilingual array.
Furthermore, the config.yaml does not expect an attribute _CertificationAtWeb_

Conclusion:
I think we have to add CertificationAtWeb here:
https://github.com/openoereb/pyramid_oereb/blob/master/pyramid_oereb/contrib/print_proxy/mapfish_print.py#L234
and add the parameter to the print config here:
https://github.com/openoereb/pyramid_oereb_mfp/blob/master/print-apps/oereb/config.yaml#L46

**Comment by voisardf** [comment]
example pdf:
[20191014053130_extract.pdf](https://github.com/openoereb/pyramid_oereb_mfp/files/3725205/20191014053130_extract.pdf)

@vvmruder @kdeininger  Could one of you two add the missing line in the pyramid_oereb mapfish_print_proxy? - I have no up to date instance on my local machine...
I'll add the necessary configuration to the pyramid_oereb_mfp project in a new PR tomorrow

**Comment by voisardf** [comment]
@vvmruder @kdeininger :  Finally I did update my local instance so I pushed the change myself in PR https://github.com/openoereb/pyramid_oereb/pull/918

**Comment by voisardf** [comment]
fixed by PR https://github.com/openoereb/pyramid_oereb_mfp/pull/35
