### ISSUE TITLE
ThemesWithoutData section has page return when more than one entry

### ISSUE THREAD

**Issue by danduk82** [openoereb/pyramid_oereb_mfp#48]
@lopo977 has found a problem during the tests for [this PR in pyramid_oereb](https://github.com/openoereb/pyramid_oereb/pull/983) (related to [this one](https://github.com/openoereb/pyramid_oereb_mfp/pull/47) in the current repo).

The problem is that when the `ThemesWithoutData` section has more than one item, there is some templating issue and jasper insert a page return as showed  [in the appended pdf](https://github.com/openoereb/pyramid_oereb_mfp/files/4086782/problem_with_themeswithoutdata.pdf) on page 2-3.

What should be done to solve this issue:
- [x] add a couple of themes that are unavailable in the test DB for `pyramid_oereb`, so that we can always check avoid this problem in the future
- [x] fix the template issue here in `pyramid_oereb_mfp`

To reproduce the bug, in `pyramid_oereb`, after launching the test server with `make serve`, lo into the test DB and add a couple of unavailable data like this:
```
# login into the test DB
docker exec -it pyramidoereb_oereb-db_1 psql -U postgres pyramid_oereb

# then in psql
insert into contaminated_military_sites.availability(fosnr, available) values (2771, FALSE);
insert into motorways_building_lines.availability(fosnr, available) values(2771, FALSE);
```
Then try to print the test pdf with
```
 curl -o ./oereb.pdf http://localhost:6543/oereb/extract/reduced/pdf/CH113928077734
```

**Comment by jwkaltz** [comment]
Fixed in #49
