### ISSUE TITLE
doubled `ExclusionOfLiability` section when it reaches exactly the bottom of TOC page

### ISSUE THREAD

**Issue by danduk82** [openoereb/pyramid_oereb_mfp#50]
When reviewing [this PR in pyramid_oereb](https://github.com/openoereb/pyramid_oereb/pull/983) a bug has been found:

When the `EclusionOfLiability` section of the TOC page in the pdf extract reaches exactly the bottom of the page, the whole section is doubled and re-printed on next page.

See : [double_disclaimer.pdf](https://github.com/openoereb/pyramid_oereb_mfp/files/4115953/double_disclaimer.pdf)

This bug is present in current `master` branch.

**Comment by jwkaltz** [comment]
Fixed in #51
