### ISSUE TITLE
vertical space above "Rechtsvorschriften" is too big

### ISSUE THREAD

**Issue by peterschaer** [openoereb/pyramid_oereb_mfp#57]
Starting with 1.7.0 we have quite a large vertical space above "Rechtsvorschriften" that hasn't been there before. It's not present above "Gesetzliche Grundlagen" and "Weitere Informationen..."

![rv_whitespace](https://user-images.githubusercontent.com/3659322/73850731-88da7300-482c-11ea-89b3-c057b6793f9b.PNG)

**Comment by jwkaltz** [comment]
This is required by the federal specification, see https://www.cadastre.ch/content/cadastre-internet/de/manual-oereb/service/extract/static/_jcr_content/contentPar/tabs_copy_copy_copy_/items/dokumente/tabPar/downloadlist/downloadItems/426_1475413822017.download/Weisung-statischer-Auszug-de.pdf , page 19.

**Comment by peterschaer** [comment]
Ok, I didn't know that. This weisung still has some secrets to unveil...

Thanks
