### ISSUE TITLE
OtherLegend (Übrige Legende) partially disappears if in a page break

### ISSUE THREAD

**Issue by jwkaltz** [openoereb/pyramid_oereb_mfp#60]
As first mentioned by @lopo977 in https://github.com/openoereb/pyramid_oereb/pull/983#issuecomment-579161738 by @lopo977 and reproduced in the current version at Schwyz (FYI @ralphschulerSZ ), the OtherLegend (Übrige Legende) mostly disappears when there is a page break within the OtherLegend:
![Screenshot from 2020-02-14 09-26-57](https://user-images.githubusercontent.com/9261252/74514108-3d028a80-4f0c-11ea-819e-374a53a9aff2.png)

**Comment by lopo977** [comment]
I propose a solution in the PR #61 
https://github.com/openoereb/pyramid_oereb_mfp/pull/61

as you can see.

[20200217101031_extract_fix_other_legend.pdf](https://github.com/openoereb/pyramid_oereb_mfp/files/4213051/20200217101031_extract_fix_other_legend.pdf)

**Comment by jwkaltz** [comment]
Fixed via #61
