### ISSUE TITLE
Version 1.7.3 blank space above "Rechtsvorschrift" in PDF-Extract

### ISSUE THREAD

**Issue by CoNussberger** [openoereb/pyramid_oereb_mfp#64]
There is too much blank space above the section "Rechtsvorschrift" in PDF-Extracts generated with mfp Version 1.7.3.

![grafik](https://user-images.githubusercontent.com/23398143/76974000-f51ebb00-6930-11ea-8a42-41db7895b739.png)

**Comment by jwkaltz** [comment]
@CoNussberger please see #57.

**Comment by CoNussberger** [comment]
Sorry for rereporting this issue... I totaly agree with @peterschaer
