### ISSUE TITLE
mapfish-print 3.23.0 non-docker does not work with oereb

### ISSUE THREAD

**Issue by jwkaltz** [openoereb/pyramid_oereb_mfp#68]
Due to the snakeyaml library regression, the mapfish-print 3.23.0 non-docker release does not work with oereb. See https://github.com/mapfish/mapfish-print/pull/1327 for the fix that was done and repairs the problem, but apparently only for the docker image. Presumably, the war published for this version needs to be redone.

**Comment by danduk82** [comment]
@jwkaltz , here is the new release:
https://github.com/mapfish/mapfish-print/releases/tag/3.23.1

can you please confirm that it works? The deps of snakeyaml are downgraded to 1.25, I think it should be OK.

**Comment by jwkaltz** [comment]
Steps to reproduce with versions prior to 3.23.1:

* Install tomcat8
* wget 
https://github.com/mapfish/mapfish-print/releases/download/3.23.0/print-servlet-3.23.0.war
* jar xf print-servlet-3.23.0.war ; rm print-servlet-3.23.0.war
* copy print-apps directory from pyramid_oereb_mfp project here
* jar --create --file print-oereb.war .
* copy print-oereb war to your tomcat webapps (by default: /var/lib/tomcat8/webapps )
* Copy a oereb print spec from some existing application (do extract/reduced/pdf/<some-egrid>?getspec=true
* Open in the browser: http://localhost:8080/print-oereb , in the drop-down "Print App/Example", select "oereb", paste your print spec from the previous step and click on "Create And Get Print"

Error: 
Request processing failed; nested exception is java.lang.RuntimeException: Error occurred while reading configuration file 'file:/var/lib/tomcat8/webapps/print-oereb/print-apps/oereb/config.yaml'
Root cause: org.yaml.snakeyaml.error.YAMLException: Number of aliases for non-scalar nodes exceeds the specified max=50

**Comment by jwkaltz** [comment]
In 3.23.1, the snakeyaml error when reading the oereb configuration file no longer occurs.

**Comment by danduk82** [comment]
@jwkaltz is this still an issue? I don't remember if it was fixed
