### ISSUE TITLE
print-servlet.war 3.23.x

### ISSUE THREAD

**Issue by voisardf** [openoereb/pyramid_oereb_mfp#69]
Hi,

from pyramid_oereb v1.5.0 up, mapfish print 3.23.1 is "required", but there seems no print-servlet.war in this version or higher is available (at least on maven) as almost everything is dockerized. But we have not dockerized our application yet.

Is there still some place I can download the print-servlet.war >=3.23.1 or do we need to compile it by ourself?

thanks

**Comment by jwkaltz** [comment]
Hi @voisardf , yes, see the links at the bottom of the page https://github.com/mapfish/mapfish-print

**Comment by voisardf** [comment]
Cheers, I missed that stopping at the Credits tag! - sorry 🙈

**Comment by jwkaltz** [comment]
No worries, in fact, it was changed not so long ago.
