### ISSUE TITLE
Add properties file for rm language

### ISSUE THREAD

**Issue by voisardf** [openoereb/pyramid_oereb_mfp#83]
To support PDF extract in romanche, we will have to add a corresponding Report_rm.properties file with all the basic translations

**Comment by jwkaltz** [comment]
@voisardf Could this be a contribution by Canton GR? I suppose they will be the only users of that.

**Comment by voisardf** [comment]
I'll take that 🙂

**Comment by voisardf** [comment]
closed by https://github.com/openoereb/pyramid_oereb_mfp/pull/84
