### ISSUE TITLE
law_status label overlaps map image when theme title is multiline

### ISSUE THREAD

**Issue by peterschaer** [openoereb/pyramid_oereb_mfp#86]
In case of a multiline theme title the law_status label is pushed down a bit and overlaps slightly with the map image:
![title_overlap](https://user-images.githubusercontent.com/3659322/145239246-e57af2c3-4e48-4149-bbc0-f2583e53c445.png)

This does not like nice and i suppose in case of a threeline theme title the overlap would be even bigger.

**Comment by voisardf** [comment]
This has to be fixed. According to the layout specialist consulted by swisstopo, the map should be pushed further down.

**Comment by voisardf** [comment]
the answer was:
> Der Abstand Titel zu Planausschnitt bleibt auch bei mehrzeiligen Titeln 12 mm (ab Schriftlinie der letzten Zeile). Der Abstand vom Planausschnitt zur folgenden Tabelle wird als Abstand 9 mm anstelle als absoluter Wert angegeben.
