### ISSUE TITLE
Layout elements not according to specifications

### ISSUE THREAD

**Issue by michmuel** [openoereb/pyramid_oereb_mfp#89]
Attached two pdf extracts with comments that describe where layout elements are not according to the federal specifications.

[CH107812348389_comments.pdf](https://github.com/openoereb/pyramid_oereb_mfp/files/8110263/CH107812348389_comments.pdf)
[CH871277778361_comments.pdf](https://github.com/openoereb/pyramid_oereb_mfp/files/8110264/CH871277778361_comments.pdf)
[json.zip](https://github.com/openoereb/pyramid_oereb_mfp/files/8110274/json.zip)

**Comment by voisardf** [comment]
https://www.cadastre.ch/content/cadastre-internet/de/manual-oereb/service/extract/static/_jcr_content/contentPar/tabs_copy_copy_copy_/items/dokumente/tabPar/downloadlist/downloadItems/426_1475413822017.download/Weisung-statischer-Auszug-de.pdf

**Comment by michmuel** [comment]
Issue was replaced by:
https://github.com/openoereb/pyramid_oereb_mfp/issues/96
https://github.com/openoereb/pyramid_oereb_mfp/issues/97
https://github.com/openoereb/pyramid_oereb_mfp/issues/98
https://github.com/openoereb/pyramid_oereb_mfp/issues/99
https://github.com/openoereb/pyramid_oereb_mfp/issues/100
https://github.com/openoereb/pyramid_oereb_mfp/issues/101
https://github.com/openoereb/pyramid_oereb_mfp/issues/102
