### ISSUE TITLE
Label "Fläche" is missing on title page

### ISSUE THREAD

**Issue by michmuel** [openoereb/pyramid_oereb_mfp#96]
The label "Fläche" is missing on the first page of the document. Only the numeric value of the area is printed on the right side of the specific line. Vertical space between "Fläche" and "Stand der amtlichen Vermessung" too large.

[CH107812348389_comments.pdf](https://github.com/openoereb/pyramid_oereb_mfp/files/8349437/CH107812348389_comments.pdf)

Specs:

https://www.cadastre.ch/content/cadastre-internet/de/manual-oereb/service/extract/static/_jcr_content/contentPar/tabs_copy_copy_copy_/items/dokumente/tabPar/downloadlist/downloadItems/426_1475413822017.download/Weisung-statischer-Auszug-de.pdf

**Comment by marionb** [comment]
@michmuel is it possible that you are not using the most recent version of the print templates?
When I compare the PDF you added them with what we currently have there are a lot of differences (most of them small but notable like spacing and so on). Can you check if this is the case? And if it is the case test with the current version.
On the current version in the development environment I can see the label "Fläche" appear.

**Comment by michmuel** [comment]
@marionb
Following files differ between our state and mfp:
- pyramid_oereb_mfp/print-apps/oereb/config.yaml --> differences only in dpi settings
- pyramid_oereb_mfp/print-apps/oereb/Report_it.properties
- pyramid_oereb_mfp/print-apps/oereb/tocConcernedTheme.jrxml
- pyramid_oereb_mfp/print-apps/oereb/topicpage.jrxml
- pyramid_oereb_mfp/print-apps/oereb/topicresponsibleoffice.jrxml

I will update our printer and report if "Fläche" is still missing.

**Comment by michmuel** [comment]
@marionb 
"Fläche" is still not printed. May it be related to the dpi values in the config.yaml?

**Comment by michmuel** [comment]
@marionb 
I also recognize some small shiftings in the position of elements. Therefore, some parts of the other issues might have been fixed. We will check that.

**Comment by marionb** [comment]
@michmuel
you mean the dpi of the map? (I have little hope that this is it but it is worth testing ;-) ) 
can you pass me the diff? or test if something changes if you set the diff the same?

**Comment by michmuel** [comment]
@marionb 
Below the diffs. I will run a test with the config.yml from pyramid_oereb_mfp.

```
103c103
<                         dpiSuggestions: [144, 254]
---
>                         dpiSuggestions: [254]
108c108
<                             dpi: 144
---
>                             dpi: 254
196c196
<                 dpiSuggestions: [144, 254]
---
>                 dpiSuggestions: [254]
201c201
<                     dpi: 144
---
>                     dpi: 254
```

**Comment by michmuel** [comment]
@marionb 
"Fläche" is also missing with the config.yml from pyramid_oereb_mfp.

**Comment by marionb** [comment]
OK I'll se if I can reproduce this somehow.

**Comment by jwkaltz** [comment]
@michmuel Just to be sure: what version of pyramid_oereb are you using to test this?

**Comment by michmuel** [comment]
@jwkaltz Until yesterday the branch concerning the availabilities/performance, now the current master, which is identical I think.

**Comment by marionb** [comment]
@michmuel
I don't really have a track to follow on this since I can not reproduce this on any other system I have checked so far.

Can you check what you have in the translation file:
https://github.com/openoereb/pyramid_oereb_mfp/blob/master/print-apps/oereb/Report_de.properties#L24

and that this property is really added her:
https://github.com/openoereb/pyramid_oereb_mfp/blob/master/print-apps/oereb/mainpage.jrxml#L212

Marion

**Comment by michmuel** [comment]
@marionb 

I guess I found the error: The area label is not printed in case `$P{Display_RealEstate_SubunitOfLandRegister} == false`. It is related to https://github.com/openoereb/pyramid_oereb/blob/9134ae187f510bf171f23c0dacaec403fc732eb7/dev/config/pyramid_oereb.yml.mako#L89 and https://github.com/openoereb/pyramid_oereb/blob/9134ae187f510bf171f23c0dacaec403fc732eb7/pyramid_oereb/contrib/print_proxy/mapfish_print/mapfish_print.py#L90.

I have no permission to push to this github project. Therefore, please find below the lines that should be inserted in file print-apps/oereb/mainpage.jrxml.

```
			<textField>
				<reportElement x="0" y="540" width="493" height="17" uuid="22ad5f4f-d1eb-4eef-ad76-4458ea1734df">
					<property name="com.jaspersoft.studio.unit.x" value="mm"/>
					<property name="com.jaspersoft.studio.unit.height" value="mm"/>
					<property name="com.jaspersoft.studio.unit.y" value="mm"/>
					<printWhenExpression><![CDATA[$P{Display_RealEstate_SubunitOfLandRegister} == false]]></printWhenExpression>
				</reportElement>
				<box bottomPadding="1">
					<topPen lineWidth="0.0" lineStyle="Solid" lineColor="#000000"/>
					<leftPen lineWidth="0.0" lineStyle="Solid" lineColor="#000000"/>
					<bottomPen lineWidth="0.2" lineStyle="Solid" lineColor="#000000"/>
					<rightPen lineWidth="0.0" lineStyle="Solid" lineColor="#000000"/>
				</box>
				<textElement verticalAlignment="Middle">
					<font fontName="Cadastra" size="8"/>
				</textElement>
				<textFieldExpression><![CDATA[$R{PropertyAreaLabel}]]></textFieldExpression>
			</textField>
``

**Comment by michmuel** [comment]
@marionb 
I made some additional changes in file print-apps/oereb/mainpage.jrxml in our test setting to correct the vertical spacing in case SubunitOfLandRegister is false.

[mainpage.jrxml.zip](https://github.com/openoereb/pyramid_oereb_mfp/files/8473144/mainpage.jrxml.zip)

**Comment by jwkaltz** [comment]
Thanks for your input @michmuel , could you prepare a PR? I have added you as maintainer of this project. Marion is currently on holidays.
