### ISSUE TITLE
Use of dashes in case there is no element for a category is not consistent

### ISSUE THREAD

**Issue by michmuel** [openoereb/pyramid_oereb_mfp#99]
Print of a dash should be consistent if there is no element for a category. See PDF page 6 "Übrige Legende (im sichtbaren Bereich)" and "Weitere Informationen und Hinweise".

I did not found in the specs if a dash is required or not, but it should be consistent. My preference: no dash.

PDF

[CH871277778361_comments.pdf](https://github.com/openoereb/pyramid_oereb_mfp/files/8349592/CH871277778361_comments.pdf)

Specs

https://www.cadastre.ch/content/cadastre-internet/de/manual-oereb/service/extract/static/_jcr_content/contentPar/tabs_copy_copy_copy_/items/dokumente/tabPar/downloadlist/downloadItems/426_1475413822017.download/Weisung-statischer-Auszug-de.pdf

**Comment by marionb** [comment]
So you want the dash or not?

Perhaps we should discuss this in general. I don't mind weather it is a dash or not. Wat speaks for a dash is that it is more comprehensible that it is not just missing something but there is really nothing to show.

**Comment by voisardf** [comment]
according to specs dash is required when lines are emtpy (other legend, documents, etc.)

**Comment by michmuel** [comment]
> according to specs dash is required when lines are emtpy (other legend, documents, etc.)

Then we should uniformly use dashes.
